### ISSUE TITLE
Coffeecup and Coffeemug not showing up

### ISSUE THREAD

**Issue by Commonlk** [Krutonium/KruFPS#25]
I tried without the mod and it worked fine but as soon I added the KruFPS again, it disappeared.

I'm not using any of the extra removes.

**Comment by Krutonium** [comment]
Did you leave them anywhere specific? They could do things like fall through a floor.

**Comment by Commonlk** [comment]
It didn't fall through the floor, I respawn it using the MSCEditor but still didn't show up, only after turning off the mod it came back. The license plates also stopped working but this time it wouldn't work even after turning off the mod.

**Comment by Krutonium** [comment]
Yeah, License Plating also doesn't work, MOP has a fix for that.
