### ISSUE TITLE
Vehicles have no engine sound after respawn

### ISSUE THREAD

**Issue by Krutonium** [Krutonium/KruFPS#3]
Don't know why, but I suspect it's something we can fix.

**Comment by Krutonium** [comment]
I've been told this is a common issue with no yet known fix, it effects modded cars too.

**Comment by Krutonium** [comment]
TODO: Examine subobjects of cars and try disabling those instead, same with Satsuma

**Comment by Athlon007** [comment]
I fixed it in #7
